apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-2x3-web
  namespace: management
spec:
  replicas: 3
  selector:
    matchLabels:
      id: m-2x3-web
  template:
    metadata:
      labels:
        id: m-2x3-web
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: httpd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    id: m-2x3-web-svc
  name: m-2x3-web-svc
  namespace: management
spec:
  ports:
  - name: 4545-80
    port: 4545
    protocol: TCP
    targetPort: 80
  selector:
    id: m-2x3-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    id: m-2x3-api
  name: m-2x3-api
  namespace: management
spec:
  replicas: 2
  selector:
    matchLabels:
      id: m-2x3-api
  template:
    metadata:
      labels:
        id: m-2x3-api
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    id: m-2x3-api-svc
  name: m-2x3-api-svc
  namespace: management
spec:
  ports:
  - name: 4546-80
    port: 4546
    protocol: TCP
    targetPort: 80
  selector:
    id: m-2x3-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: runner
    tag: light
  name: m-3cc-runner
  namespace: management
spec:
  replicas: 2
  selector:
    matchLabels:
      id: m-3cc-runner
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: m-3cc-runner
    spec:
      containers:
      - image: python:3.7.4-alpine3.9
        name: python
        args: ['sh', '-c', 'sleep 2d']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: runner
    tag: heavy
  name: m-3cc-runner-heavy
  namespace: management
spec:
  replicas: 2
  selector:
    matchLabels:
      id: m-3cc-runner-heavy
  template:
    metadata:
      labels:
        id: m-3cc-runner-heavy
    spec:
      containers:
      - image: python:3.7.4-alpine3.9
        name: python
        args: ['sh', '-c', 'sleep 2d']

