apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: important-pod
  name: important-pod
  namespace: management
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: important
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  priorityClassName: high-priority-important
status: {}